- name: Pruebas varias
  hosts: all
  tasks:
    - name: Instalamos paquetes necesarios
      package:
        name: "{{ item }}"
        state: present 
      loop:
        - git
        - tree
        - apache2
        - wget
        - curl
        - apt-transport-https 
        - ca-certificates
        - gnupg-agent
        - software-properties-common 
